services:
  redis:
    image: redis:7-alpine
    container_name: ticketmain-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # postgres:
  #   image: postgres:15 ...

volumes:
  redis_data: